version: '3.7'
services:
  phpdeps:
    image: prooph/composer:7.3
    volumes:
      - .:/app
    command: install
  assets:
    image: node:10
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run watch"
  web:
    depends_on:
      - "phpdeps"
      - "assets"
      - "redis"
    build: .
    working_dir: /html
    volumes:
      - .:/html
    ports: 
    - "8080:80"
  redis:
    image: redis
    container_name: redis